"""Integration tests for ``justorm.oracledb``.

These tests require a running Oracle instance and the
``python-oracledb`` package.  Both are opt-in: set
``JUSTORM_ORACLE_DSN`` and install the ``oracledb`` extra.

Oracle is where justorm's dialect-specific surface matters most:

* identifiers are quoted with double quotes (Oracle folds unquoted
  identifiers to upper case, so justorm always quotes and the tests
  create their tables with quoted names),
* placeholders are **named** (``:p<hex>``), generated by the builder;
  parameters are passed to the driver as a dict,
* ``RETURNING`` requires an OUT bind variable and is not modelled,
* upserts use ``MERGE``, which justorm does not model,
* ``DISTINCT ON`` and ``ILIKE`` are not available,
* ``FOR UPDATE`` is supported, with ``NOWAIT`` / ``SKIP LOCKED``,
* ``LIMIT`` / ``OFFSET`` map to ``OFFSET ... ROWS FETCH NEXT ...
  ROWS ONLY`` (12c+); no ``ORDER BY`` is required,
* ``DEFAULT`` is not accepted inside a ``VALUES`` list.

The shared builder logic is exercised in ``test_builder.py``; here we
check that Oracle accepts the SQL justorm generates, and that the
things Oracle does not have are rejected before they reach the server.
"""

from __future__ import annotations

from collections import namedtuple

import pytest

oracledb = pytest.importorskip("oracledb")

import justorm.oracledb
from justorm import JustormDialectError, JustormError


pytestmark = pytest.mark.oracledb


# ---------------------------------------------------------------------------
# Cursor creation
#
# ``oracledb.Connection.cursor()`` returns the driver's own cursor and
# does not accept a replacement class, so the justorm cursor is
# constructed directly from the connection.
# ---------------------------------------------------------------------------


def _cursor(conn):
    return justorm.oracledb.Cursor(conn)


# ---------------------------------------------------------------------------
# Cursor identity and native surface
# ---------------------------------------------------------------------------


class TestCursorIdentity:
    def test_cursor_is_oracledb_cursor(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            assert isinstance(cur, oracledb.Cursor)
        finally:
            cur.close()

    def test_dialect_name(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            assert cur.dialect_name == "oracledb"
        finally:
            cur.close()

    def test_native_execute_returns_cursor(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            # python-oracledb's ``execute`` returns the cursor, so the
            # justorm wrapper does too.
            result = cur.execute("SELECT 1 FROM DUAL")
            assert result is cur
            assert cur.fetchone() == (1,)
        finally:
            cur.close()

    def test_table_named_like_a_cursor_attribute(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            assert callable(cur.execute)
            assert cur.table("execute") is not None
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def users_table(oracle_conn):
    """A small ``users`` table with a unique ``name`` column.

    All identifiers are quoted, so the table is created with the exact
    lower-case name justorm will produce when it renders
    ``cur.table("users")``.
    """
    cur = _cursor(oracle_conn)
    try:
        cur.execute(
            """
            CREATE TABLE "users" (
                "id"     NUMBER GENERATED BY DEFAULT AS IDENTITY
                         PRIMARY KEY,
                "name"   VARCHAR2(64) NOT NULL,
                "age"    NUMBER,
                "active" NUMBER(1) DEFAULT 1 NOT NULL,
                CONSTRAINT "uq_users_name" UNIQUE ("name")
            )
            """
        )
        cur.table("users").insert(
            [
                {"name": "Alice", "age": 30, "active": 1},
                {"name": "Bob", "age": 25, "active": 1},
                {"name": "Carol", "age": 40, "active": 0},
            ]
        )
    finally:
        cur.close()
    return "users"


# ---------------------------------------------------------------------------
# fetch* with format=
# ---------------------------------------------------------------------------


class TestFetchFormat:
    def test_fetchone_default(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id", "name" FROM "users" ORDER BY "id"')
            row = cur.fetchone()
            assert isinstance(row, tuple)
            assert row[1] == "Alice"
        finally:
            cur.close()

    def test_fetchone_dict(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id", "name" FROM "users" ORDER BY "id"')
            row = cur.fetchone(format=dict)
            assert row == {"id": 1, "name": "Alice"}
        finally:
            cur.close()

    def test_fetchone_namedtuple(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id", "name" FROM "users" ORDER BY "id"')
            row = cur.fetchone(format=namedtuple)
            assert row.id == 1
            assert row.name == "Alice"
        finally:
            cur.close()

    def test_fetchone_none_with_format(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id" FROM "users" WHERE 1 = 0')
            assert cur.fetchone(format=dict) is None
            assert cur.fetchone(format=namedtuple) is None
        finally:
            cur.close()

    def test_fetchmany_dict(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id", "name" FROM "users" ORDER BY "id"')
            rows = cur.fetchmany(2, format=dict)
            assert rows == [
                {"id": 1, "name": "Alice"},
                {"id": 2, "name": "Bob"},
            ]
        finally:
            cur.close()

    def test_fetchall_namedtuple(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id", "name" FROM "users" ORDER BY "id"')
            rows = cur.fetchall(format=namedtuple)
            assert rows[2].name == "Carol"
        finally:
            cur.close()

    def test_bad_format_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('SELECT "id" FROM "users"')
            with pytest.raises(JustormError):
                cur.fetchall(format=list)
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# get
# ---------------------------------------------------------------------------


class TestGet:
    def test_get_row(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            row = cur.table("users").where(name="Alice").get()
            assert row == {
                "id": 1,
                "name": "Alice",
                "age": 30,
                "active": 1,
            }
        finally:
            cur.close()

    def test_get_missing_returns_none(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            assert cur.table("users").where(name="Nobody").get() is None
        finally:
            cur.close()

    def test_get_default(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            assert cur.table("users").where(name="Nobody").get(default={}) == {}
        finally:
            cur.close()

    def test_get_scalar(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            assert cur.table("users").where(name="Alice").get("name") == "Alice"
        finally:
            cur.close()

    def test_get_tuple(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            row = cur.table("users").where(name="Alice").get(("id", "name"))
            assert row == (1, "Alice")
        finally:
            cur.close()

    def test_get_rejects_key(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormError):
                cur.table("users").where(name="Alice").get(key="id")
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# query
# ---------------------------------------------------------------------------


class TestQuery:
    def test_query_select_returns_dicts(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = cur.query(
                'SELECT "id", "name" FROM "users" ORDER BY "id"'
            )
            assert rows == [
                {"id": 1, "name": "Alice"},
                {"id": 2, "name": "Bob"},
                {"id": 3, "name": "Carol"},
            ]
        finally:
            cur.close()

    def test_query_select_with_params(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = cur.query(
                'SELECT "name" FROM "users" '
                'WHERE "age" > :p1 ORDER BY "id"',
                {"p1": 26},
            )
            assert rows == [{"name": "Alice"}, {"name": "Carol"}]
        finally:
            cur.close()

    def test_query_select_empty(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            assert (
                cur.query('SELECT "id" FROM "users" WHERE 1 = 0')
                == []
            )
        finally:
            cur.close()

    def test_query_insert_returns_rowcount(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            result = cur.query(
                'INSERT INTO "users" ("name", "age") '
                "VALUES (:p1, :p2)",
                {"p1": "Dave", "p2": 50},
            )
            # python-oracledb exposes ``lastrowid`` as a rowid string,
            # not an int, so ``query`` falls back to rowcount for
            # INSERT statements.
            assert result == 1
        finally:
            cur.close()

    def test_query_update_returns_rowcount(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            result = cur.query(
                'UPDATE "users" SET "age" = :p1 WHERE "age" > :p2',
                {"p1": 99, "p2": 28},
            )
            assert result == 2
        finally:
            cur.close()

    def test_query_delete_returns_rowcount(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            result = cur.query(
                'DELETE FROM "users" WHERE "name" = :p1',
                {"p1": "Bob"},
            )
            assert result == 1
        finally:
            cur.close()

    def test_query_ddl_returns_int(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            result = cur.query('CREATE TABLE "t" ("id" NUMBER)')
            assert isinstance(result, int)
        finally:
            cur.close()

    def test_query_bad_sql_raises(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(oracledb.Error):
                cur.query('SELECT * FROM "no_such_table"')
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# SELECT
# ---------------------------------------------------------------------------


class TestSelect:
    def test_select_all(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = cur.table("users").orderby("id").select()
            assert len(rows) == 3
            assert {r["name"] for r in rows} == {"Alice", "Bob", "Carol"}
        finally:
            cur.close()

    def test_identifier_quoting_uses_double_quotes(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            # Reserved words as quoted identifiers must round-trip.
            cur.execute(
                'CREATE TABLE "select" ("where" NUMBER, "order" NUMBER)'
            )
            cur.table("select").append(**{"where": 1, "order": 2})
            rows = cur.table("select").select()
            assert rows == [{"where": 1, "order": 2}]
        finally:
            cur.close()

    def test_where_kwargs(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = cur.table("users").where(name="Alice").select()
            assert len(rows) == 1
            assert rows[0]["age"] == 30
        finally:
            cur.close()

    def test_select_scalar(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            names = cur.table("users").orderby("id").select("name")
            assert names == ["Alice", "Bob", "Carol"]
        finally:
            cur.close()

    def test_select_tuple(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = (
                cur.table("users")
                .orderby("id")
                .select(("id", "name"))
            )
            assert all(isinstance(r, tuple) for r in rows)
            assert rows[0][1] == "Alice"
        finally:
            cur.close()

    def test_select_keyed(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            mapping = cur.table("users").select("name", key="id")
            assert set(mapping.values()) == {"Alice", "Bob", "Carol"}
        finally:
            cur.close()

    def test_limit_and_offset(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = (
                cur.table("users")
                .orderby("id")
                .limit(2)
                .offset(1)
                .select("name")
            )
            assert rows == ["Bob", "Carol"]
        finally:
            cur.close()

    def test_limit_without_offset(self, oracle_conn, users_table):
        # Oracle's ``FETCH NEXT`` does not require an ORDER BY.
        cur = _cursor(oracle_conn)
        try:
            rows = cur.table("users").limit(2).select("name")
            assert len(rows) == 2
        finally:
            cur.close()

    def test_parameter_is_not_inlined(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            rows = (
                cur.table("users")
                .where(name="x'; DROP TABLE users; --")
                .select()
            )
            assert rows == []
            assert cur.table("users").select() is not None
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# INSERT
# ---------------------------------------------------------------------------


class TestInsert:
    def test_append(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            assert (
                cur.table("users").append(name="Dave", age=50) is None
            )
            assert (
                len(cur.table("users").where(name="Dave").select()) == 1
            )
        finally:
            cur.close()

    def test_insert_many_rows(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.table("users").insert([
                {"name": "G", "age": 1},
                {"name": "H", "age": 2},
                {"name": "I", "age": 3},
            ])
            assert (
                len(
                    cur.table("users")
                    .where_in(name=["G", "H", "I"])
                    .select()
                )
                == 3
            )
        finally:
            cur.close()

    def test_insert_missing_key_uses_null(self, oracle_conn):
        # Oracle does not accept ``DEFAULT`` inside a VALUES list, so
        # justorm substitutes NULL on that dialect.
        cur = _cursor(oracle_conn)
        try:
            cur.execute(
                'CREATE TABLE "t" ('
                '  "id" NUMBER GENERATED BY DEFAULT AS IDENTITY '
                '       PRIMARY KEY, '
                '  "a" NUMBER, '
                '  "b" NUMBER DEFAULT 99'
                ")"
            )
            cur.table("t").insert([{"a": 1, "b": 2}, {"a": 3}])
            rows = cur.table("t").orderby("a").select()
            assert rows[0]["b"] == 2
            # Oracle does not accept DEFAULT inside a VALUES list, so
            # justorm substitutes NULL: the column's own DEFAULT 99 is
            # never triggered.
            assert rows[1]["b"] is None
        finally:
            cur.close()

    def test_insert_many(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.table("users").insert_many(
                [{"name": "J", "age": 1}, {"name": "K", "age": 2}],
                columns=["name", "age"],
            )
            assert (
                len(
                    cur.table("users")
                    .where_in(name=["J", "K"])
                    .select()
                )
                == 2
            )
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# UPDATE / DELETE
# ---------------------------------------------------------------------------


class TestUpdateDelete:
    def test_update(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.table("users").where(name="Alice").update(age=31)
            assert (
                cur.table("users").where(name="Alice").select()[0]["age"]
                == 31
            )
        finally:
            cur.close()

    def test_update_without_where_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormError):
                cur.table("users").update(age=0)
        finally:
            cur.close()

    def test_delete(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.table("users").where(name="Bob").delete()
            assert cur.table("users").where(name="Bob").select() == []
        finally:
            cur.close()

    def test_delete_without_where_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormError):
                cur.table("users").delete()
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# RETURNING is rejected
# ---------------------------------------------------------------------------


class TestReturningRejected:
    def test_append_returning_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").returning("id").append(
                    name="X", age=1
                )
        finally:
            cur.close()

    def test_update_returning_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").where(name="Alice").returning("id").update(
                    age=1
                )
        finally:
            cur.close()

    def test_delete_returning_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").where(name="Alice").returning("id").delete()
        finally:
            cur.close()

    def test_returning_into_workaround(self, oracle_conn, users_table):
        # The documented workaround on Oracle: RETURNING ... INTO
        # with an OUT bind variable, written as raw SQL.
        cur = _cursor(oracle_conn)
        try:
            var = cur.var(oracledb.NUMBER)
            cur.execute(
                'INSERT INTO "users" ("name", "age") '
                "VALUES (:p1, :p2) RETURNING \"id\" INTO :p3",
                {"p1": "Zed", "p2": 1, "p3": var},
            )
            assert var.getvalue() == [4]
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# UPSERT is rejected
# ---------------------------------------------------------------------------


class TestUpsertRejected:
    def test_on_conflict_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").on_conflict(
                    do=cur.sql.nothing()
                ).append(name="X", age=1)
        finally:
            cur.close()

    def test_on_duplicate_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").on_duplicate(
                    update={"age": 1}
                ).append(name="X", age=1)
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Dialect-specific features
# ---------------------------------------------------------------------------


class TestDialectSpecific:
    def test_ilike_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").where_ilike(name="alice").select()
        finally:
            cur.close()

    def test_distinct_on_rejected(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(JustormDialectError):
                cur.table("users").distinct_on("name").select()
        finally:
            cur.close()

    def test_for_update_supported(self, oracle_conn, users_table):
        # Oracle supports FOR UPDATE (no FOR SHARE, though -- the
        # renderer maps ``share=True`` to FOR UPDATE).
        cur = _cursor(oracle_conn)
        try:
            rows = (
                cur.table("users")
                .where(name="Alice")
                .select(for_update=True)
            )
            assert len(rows) == 1
        finally:
            cur.close()

    def test_distinct_works(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            cur.execute('CREATE TABLE "t" ("a" NUMBER)')
            cur.table("t").insert([{"a": 1}, {"a": 1}, {"a": 2}])
            rows = cur.table("t").distinct().orderby("a").select("a")
            assert rows == [1, 2]
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Subquery
# ---------------------------------------------------------------------------


class TestSubquery:
    def test_subquery_join(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            cur.execute(
                'CREATE TABLE "orders" ('
                '  "id"      NUMBER GENERATED BY DEFAULT AS IDENTITY '
                '            PRIMARY KEY, '
                '  "user_id" NUMBER NOT NULL, '
                '  "total"   NUMBER NOT NULL'
                ")"
            )
            cur.table("orders").insert(
                [
                    {"user_id": 1, "total": 50},
                    {"user_id": 1, "total": 200},
                    {"user_id": 2, "total": 10},
                ]
            )

            users = cur.table("users")
            orders = cur.table("orders")

            sub = orders.where(
                orders["total"] > 100
            ).select_subquery({"user_id"})
            s = sub.as_("s")

            rows = users.join(
                s, on=users["id"] == s["user_id"]
            ).select({users["name"]})
            assert [r["name"] for r in rows] == ["Alice"]
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Nested subqueries
# ---------------------------------------------------------------------------


class TestNestedSubquery:
    @pytest.fixture()
    def three_tables(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            cur.execute(
                'CREATE TABLE "users" ('
                '  "id"   NUMBER GENERATED BY DEFAULT AS IDENTITY '
                '         PRIMARY KEY, '
                '  "name" VARCHAR2(64) NOT NULL'
                ")"
            )
            cur.execute(
                'CREATE TABLE "orders" ('
                '  "id"      NUMBER GENERATED BY DEFAULT AS IDENTITY '
                '            PRIMARY KEY, '
                '  "user_id" NUMBER NOT NULL, '
                '  "total"   NUMBER NOT NULL'
                ")"
            )
            cur.execute(
                'CREATE TABLE "order_items" ('
                '  "id"       NUMBER GENERATED BY DEFAULT AS IDENTITY '
                '             PRIMARY KEY, '
                '  "order_id" NUMBER NOT NULL, '
                '  "qty"      NUMBER NOT NULL'
                ")"
            )
            cur.table("users").insert([
                {"name": "Alice"},
                {"name": "Bob"},
            ])
            cur.table("orders").insert([
                {"user_id": 1, "total": 50},
                {"user_id": 1, "total": 200},
                {"user_id": 2, "total": 10},
            ])
            cur.table("order_items").insert([
                {"order_id": 2, "qty": 3},
                {"order_id": 2, "qty": 4},
                {"order_id": 3, "qty": 1},
            ])
        finally:
            cur.close()
        return "users"

    def test_two_subqueries_joined(self, oracle_conn, three_tables):
        cur = _cursor(oracle_conn)
        try:
            users = cur.table("users")
            orders = cur.table("orders")
            items = cur.table("order_items")

            big_orders = orders.where(
                orders["total"] > 100
            ).select_subquery({"id", "user_id"})
            item_ids = items.where(
                items["qty"] > 2
            ).select_subquery({"order_id"})
            bo = big_orders.as_("bo")
            it = item_ids.as_("it")

            rows = users.join(
                bo, on=users["id"] == bo["user_id"]
            ).join(
                it, on=bo["id"] == it["order_id"]
            ).select({users["name"]})
            # Two order_items rows match the same big order, so Alice
            # appears twice.
            assert [r["name"] for r in rows] == ["Alice", "Alice"]
        finally:
            cur.close()

    def test_subquery_with_join_inside(self, oracle_conn, three_tables):
        cur = _cursor(oracle_conn)
        try:
            users = cur.table("users")
            orders = cur.table("orders")

            inner = users.join(
                orders,
                on=users["id"] == orders["user_id"],
            ).where(
                orders["total"] > 100
            ).select_subquery({users["id"]})
            s = inner.as_("s")

            rows = s.select()
            assert [r["id"] for r in rows] == [1]
        finally:
            cur.close()

    def test_subquery_with_group_style_filter(self, oracle_conn, three_tables):
        cur = _cursor(oracle_conn)
        try:
            users = cur.table("users")
            orders = cur.table("orders")

            big = orders.where(
                orders["total"] > 100
            ).select_subquery({"user_id"})
            s = big.as_("s")

            rows = users.join(
                s, on=users["id"] == s["user_id"]
            ).select({users["name"]})
            assert [r["name"] for r in rows] == ["Alice"]
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Errors from the server
# ---------------------------------------------------------------------------


class TestServerErrors:
    def test_missing_table(self, oracle_conn):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(oracledb.Error):
                cur.table("no_such_table").select()
        finally:
            cur.close()

    def test_missing_column(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            with pytest.raises(oracledb.Error):
                cur.table("users").where(no_such_column=1).select()
        finally:
            cur.close()


# ---------------------------------------------------------------------------
# Transactions
# ---------------------------------------------------------------------------


class TestTransactions:
    def test_rollback_discards_insert(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            # The fixture runs with autocommit on, so to test rollback
            # we explicitly disable it for the duration of the test.
            oracle_conn.autocommit = False
            cur.table("users").append(name="Temp", age=1)
            oracle_conn.rollback()
            assert cur.table("users").where(name="Temp").select() == []
        finally:
            oracle_conn.autocommit = True
            cur.close()

    def test_commit_persists_insert(self, oracle_conn, users_table):
        cur = _cursor(oracle_conn)
        try:
            oracle_conn.autocommit = False
            cur.table("users").append(name="Persist", age=1)
            oracle_conn.commit()
            assert (
                len(cur.table("users").where(name="Persist").select()) == 1
            )
        finally:
            oracle_conn.autocommit = True
            cur.close()